name: Ruby Unit Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goo-slice: [ '20', '100', '500' ]
        ruby-version: [ '2.7', '3.0' ]
        triplestore: [ 'fs', 'ag', 'vo', 'gb' ]

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get -y install raptor2-utils
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Add config file
      # tempoaray workaround for the config.rb file requirement
      run:  echo 'Goo.config do |config| end' > config/config.rb
    - name: List directory contents
      run: ls -R ./test/data
    - name: Run tests
      run: GOO_SLICES=${{ matrix.goo-slice }} bundle exec rake test:docker:${{ matrix.triplestore }} TESTOPTS="-v"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        verbose: true
